# Generated by Django 4.1.13 on 2024-06-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.CharField(max_length=10, unique=True)),
                ('aprendices_actuales', models.IntegerField()),
                ('aprendices_matriculados', models.IntegerField()),
                ('jornada', models.CharField(max_length=6)),
                ('tipo_formacion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('correo_electronico', models.CharField(max_length=50, unique=True)),
                ('genero', models.CharField(max_length=9)),
            ],
        ),
    ]
